//action login
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const CLEAR_USER = 'CLEAR_USER';

//action language
export const FETCH_LANGUAGE = 'FETCH_LANGUAGE';
export const FETCH_LANGUAGE_SUCCESS = 'FETCH_LANGUAGE_SUCCESS';
export const FETCH_LANGUAGE_FAILED = 'FETCH_LANGUAGE_FAILED';
export const DELETE_LANGUAGE = 'DELETE_LANGUAGE';

//action menu
export const FETCH_MENU = 'FETCH_MENU';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAILED = 'FETCH_MENU_FAILED';
export const DELETE_MENU = 'DELETE_MENU';

//action noti
export const FETCH_NOTI = 'FETCH_NOTI';
export const FETCH_NOTI_SUCCESS = 'FETCH_NOTI_SUCCESS';
export const FETCH_NOTI_FAILED = 'FETCH_NOTI_FAILED';
export const DELETE_NOTI = 'DELETE_NOTI';

//action Personal Information
export const FETCH_TTCN = 'GET_TTCN';
export const FETCH_TTCN_SUCCESS = 'GET_TTCN_SUCCESS';
export const FETCH_TTCN_FAILED = 'GET_TTCN_FAILED';
export const DELETE_TTCN = 'DELETE_TTCN';

//action working daily
export const FETCH_WORKING_DAILY = 'FETCH_WORKING_DAILY';
export const FETCH_WORKING_DAILY_SUCCESS = 'FETCH_WORKING_DAILY_SUCCESS';
export const FETCH_WORKING_DAILY_FAILED = 'FETCH_WORKING_DAILY_FAILED';
export const DELETE_WORKING_DAILY = 'DELETE_WORKING_DAILY';

//action VPCC
export const FETCH_VPCC = 'FETCH_VPCC';
export const FETCH_VPCC_SUCCESS = 'FETCH_VPCC_SUCCESS';
export const FETCH_VPCC_FAILED = 'FETCH_VPCC_FAILED';
export const DELETE_VPCC = 'DELETE_VPCC';

// //action working monthly
// export const FETCH_WORKING_MONTHLY = 'FETCH_WORKING_MONTHLY';
// export const FETCH_WORKING_MONTHLY_SUCCESS = 'FETCH_WORKING_MONTHLY_SUCCESS';
// export const FETCH_WORKING_MONTHLY_FAILED = 'FETCH_WORKING_MONTHLY_FAILED';

//action salary month
export const FETCH_SALARY_MONTH = 'FETCH_SALARY_MONTH';
export const FETCH_SALARY_MONTH_SUCCESS = 'FETCH_SALARY_MONTH_SUCCESS';
export const FETCH_SALARY_MONTH_FAILED = 'FETCH_SALARY_MONTH_FAILED';
export const DELETE_SALARY_MONTH = 'DELETE_SALARY_MONTH';

//action absence information
export const FETCH_ABSENCE_INFORMATION = 'FETCH_ABSENCE_INFORMATION';
export const FETCH_ABSENCE_INFORMATION_SUCCESS =
  'FETCH_ABSENCE_INFORMATION_SUCCESS';
export const FETCH_ABSENCE_INFORMATION_FAILED =
  'FETCH_ABSENCE_INFORMATION_FAILED';
export const DELETE_ABSENCE_INFORMATION = 'DELETE_ABSENCE_INFORMATION';

//action Attendance History
export const FETCH_ATTENDANCE_HISTORY = 'FETCH_ATTENDANCE_HISTORY';
export const FETCH_ATTENDANCE_HISTORY_SUCCESS =
  'FETCH_ATTENDANCE_HISTORY_SUCCESS';
export const FETCH_ATTENDANCE_HISTORY_FAILED =
  'FETCH_ATTENDANCE_HISTORY_FAILED';
export const DELETE_ATTENDANCE_HISTORY = 'DELETE_ATTENDANCE_HISTORY';

//action XCTC
export const FETCH_XNTC = 'FETCH_XNTC';
export const FETCH_XNTC_SUCCESS = 'FETCH_XNTC_SUCCESS';
export const FETCH_XNTC_FAILED = 'FETCH_XNTC_FAILED';
export const POST_XNTC = 'POST_XNTC';
export const POST_XNTC_SUCCESS = 'POST_XNTC_SUCCESS';
export const POST_XNTC_FAILED = 'POST_XNTC_FAILED';
export const DELETE_XNTC = 'DELETE_XNTC';

//action NPD
export const FETCH_NPD = 'FETCH_NPD';
export const FETCH_NPD_SUCCESS = 'FETCH_NPD_SUCCESS';
export const FETCH_NPD_FAILED = 'FETCH_NPD_FAILED';

//action DKV
export const FETCH_DKV = 'FETCH_DKV';
export const FETCH_DKV_SUCCESS = 'FETCH_DKV_SUCCESS';
export const FETCH_DKV_FAILED = 'FETCH_DKV_FAILED';
export const DELETE_DKV = 'DELETE_DKV';

//action DKVV2
export const FETCH_DKVV2 = 'FETCH_DKVV2';
export const FETCH_DKVV2_SUCCESS = 'FETCH_DKVV2_SUCCESS';
export const FETCH_DKVV2_FAILED = 'FETCH_DKVV2_FAILED';
export const DELETE_DKVV2 = 'DELETE_DKVV2';
//action DKDT-VS
export const FETCH_DKDT_VS = 'FETCH_DKDT_VS';
export const FETCH_DKDT_VS_SUCCESS = 'FETCH_DKDT_VS_SUCCESS';
export const FETCH_DKDT_VS_FAILED = 'FETCH_DKDT_VS_FAILED';
export const DELETE_DKDT_VS = 'DELETE_DKDT_VS';

//action PDDT-VS
export const FETCH_PDDT_VS = 'FETCH_PDDT_VS';
export const FETCH_PDDT_VS_SUCCESS = 'FETCH_PDDT_VS_SUCCESS';
export const FETCH_PDDT_VS_FAILED = 'FETCH_PDDT_VS_FAILE';
export const DELETE_PDDT_VS = 'DELETE_PDDT_VS';

//action PDTC
export const FETCH_PD_TC = 'FETCH_PD_TC';
export const FETCH_PDTC_SUCCESS = 'FETCH_PDTC_SUCCESS';
export const FETCH_PDTC_FAILED = 'FETCH_PDTC_FAILED';
export const DELETE_PDTC = 'DELETE_PDTC';

// reset store
export const RESET_STORE = 'RESET_STORE';

// export const GET_INFOR = 'GET_INFOR';
// export const GET_MENU_HRIN = 'GET_MENU_HRIN';
// export const GET_LANGUGE = 'GET_LANGUGE';
// export const ADD_LANGUGE = 'ADD_LANGUGE';
// export const CHANGE_LANGUGE = 'CHANGE_LANGUGE';
// export const GET_MENU_HRRE = 'GET_MENU_HRRE';
// export const GET_MENU_HRAP = 'GET_MENU_HRAP';
// export const GET_MENU_HRTI = 'GET_MENU_HRTI';
// export const GET_MENU_HRTK = 'GET_MENU_HRTK';
// export const GET_MENU_HRDT = 'GET_MENU_HRDT';
// export const GET_MENU_HRMN = 'GET_MENU_HRMN';
// export const GET_MENU = 'GET_MENU';
// export const GET_USERNAME = 'GET_USERNAME';
// export const GET_PASS = 'GET_PASS';
// export const GET_STATUS = 'GET_STATUS';
// export const GET_VALUE_AUTHEN = 'GET_VALUE_AUTHEN';
// export const GET_FINGER = 'GET_FINGER';

export const ITEM_QR_DEFAULT = 'ITEM_QR_DEFAULT';
export const ITEM_QR_DEFAULT_SUCCESS = 'ITEM_QR_DEFAULT_SUCCESS';
export const ITEM_QR_DEFAULT_FAILED = 'ITEM_QR_DEFAULT_FAILED';
