import Back from './Back';
import BDTK from './BDTK';
import Ca from './Calendar';
import CC from './CC';
import BaChatck from './Chat';
import DKDL from './DKDL';
import Drop from './Drop';
import Email from './Email';
import Face from './Face';
import Finger from './Finger';
import Home from './Home';
import Infor from './Infor';
import Next_sp from './Next_sp';
import Next from './Next';
import Noti from './Noti';
import Password from './Password';
import QLDL from './QLDL';
import QLDT from './QLDT';
import QLPD from './QLPD';
import Search from './Search';
import ST from './ST';
import System from './System';
import TB from './TB';
import Time from './Time';
import Translate from './Translate';
import TVTT from './TVTT';
import User from './User';


